//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoPlantillaPersonal.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cuenta
    {
        public int idCuenta { get; set; }
        public string usuario { get; set; }
        public string contrasenia { get; set; }
        public string tipo { get; set; }
        public string nombre { get; set; }
        public string apellidoPaterno { get; set; }
        public string apellidoMaterno { get; set; }
    }
}
