//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoPlantillaPersonal.Modelos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SistemaPlantillaPersonalEntities : DbContext
    {
        public SistemaPlantillaPersonalEntities()
            : base("name=SistemaPlantillaPersonalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ClavePresupuestal> ClavePresupuestal { get; set; }
        public DbSet<Cuenta> Cuenta { get; set; }
        public DbSet<Plantilla> Plantilla { get; set; }
        public DbSet<PlantillaHistorial> PlantillaHistorial { get; set; }
        public DbSet<RelacionLaboral> RelacionLaboral { get; set; }
        public DbSet<Sector> Sector { get; set; }
        public DbSet<Status> Status { get; set; }
    }
}
