//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoPlantillaPersonal.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plantilla
    {
        public int idPlantilla { get; set; }
        public int PBPNUE { get; set; }
        public string RFC { get; set; }
        public string NMAPP { get; set; }
        public string NMAPM { get; set; }
        public string NMNOMB { get; set; }
        public string NMNOM { get; set; }
        public System.DateTime NMFING { get; set; }
        public string NIVEL { get; set; }
        public string CNOMCVE { get; set; }
        public string CNOMTIP { get; set; }
        public string CTICCVE { get; set; }
        public string CVEDEP { get; set; }
        public string NQS { get; set; }
        public int idSector { get; set; }
        public int idClavePresupuestal { get; set; }
        public int idStatus { get; set; }
        public int idRelacionLaboral { get; set; }
    
        public virtual ClavePresupuestal ClavePresupuestal { get; set; }
        public virtual RelacionLaboral RelacionLaboral { get; set; }
        public virtual Sector Sector { get; set; }
        public virtual Status Status { get; set; }
    }
}
